package samebutdifferent.ecologics.registry;

import java.util.function.Supplier;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.FlowerPotBlock;
import net.minecraft.world.level.block.LeavesBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SaplingBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import samebutdifferent.ecologics.block.AzaleaFlowerBlock;
import samebutdifferent.ecologics.block.AzaleaLogBlock;
import samebutdifferent.ecologics.block.CoconutBlock;
import samebutdifferent.ecologics.block.CoconutLeavesBlock;
import samebutdifferent.ecologics.block.CoconutSaplingBlock;
import samebutdifferent.ecologics.block.FloweringAzaleaLogBlock;
import samebutdifferent.ecologics.block.HangingCoconutBlock;
import samebutdifferent.ecologics.block.ModCeilingHangingSignBlock;
import samebutdifferent.ecologics.block.ModStandingSignBlock;
import samebutdifferent.ecologics.block.ModWallHangingSignBlock;
import samebutdifferent.ecologics.block.ModWallSignBlock;
import samebutdifferent.ecologics.block.MossLayerBlock;
import samebutdifferent.ecologics.block.PotBlock;
import samebutdifferent.ecologics.block.PricklyPearBlock;
import samebutdifferent.ecologics.block.SandcastleBlock;
import samebutdifferent.ecologics.block.SeashellBlock;
import samebutdifferent.ecologics.block.SurfaceMossBlock;
import samebutdifferent.ecologics.block.ThinIceBlock;
import samebutdifferent.ecologics.block.grower.ModTreeGrower;
import samebutdifferent.ecologics.block.properties.ModWoodType;
import samebutdifferent.ecologics.platform.CommonPlatformHelper;

public class ModBlocks {
    public static void init() {}

    public static final Supplier<RotatedPillarBlock> COCONUT_LOG = registerBlock("coconut_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG)));
    public static final Supplier<RotatedPillarBlock> STRIPPED_COCONUT_LOG = registerBlock("stripped_coconut_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_LOG)));
    public static final Supplier<RotatedPillarBlock> COCONUT_WOOD = registerBlock("coconut_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD)));
    public static final Supplier<RotatedPillarBlock> STRIPPED_COCONUT_WOOD = registerBlock("stripped_coconut_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_WOOD)));
    public static final Supplier<CoconutLeavesBlock> COCONUT_LEAVES = registerBlock("coconut_leaves", () -> new CoconutLeavesBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES)));
    public static final Supplier<Block> COCONUT_PLANKS = registerBlock("coconut_planks", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<SlabBlock> COCONUT_SLAB = registerBlock("coconut_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<StairBlock> COCONUT_STAIRS = registerBlock("coconut_stairs", () -> new StairBlock(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceBlock> COCONUT_FENCE = registerBlock("coconut_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceGateBlock> COCONUT_FENCE_GATE = registerBlock("coconut_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<DoorBlock> COCONUT_DOOR = registerBlock("coconut_door", () -> new DoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_DOOR)){});
    public static final Supplier<TrapDoorBlock> COCONUT_TRAPDOOR = registerBlock("coconut_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_TRAPDOOR)){});
    public static final Supplier<ButtonBlock> COCONUT_BUTTON = registerBlock("coconut_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON)) {});
    public static final Supplier<PressurePlateBlock> COCONUT_PRESSURE_PLATE = registerBlock("coconut_pressure_plate", () -> new PressurePlateBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE)) {});
    public static final Supplier<ModStandingSignBlock> COCONUT_SIGN = CommonPlatformHelper.registerBlock("coconut_sign", () -> new ModStandingSignBlock(ModWoodType.COCONUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallSignBlock> COCONUT_WALL_SIGN = CommonPlatformHelper.registerBlock("coconut_wall_sign", () -> new ModWallSignBlock(ModWoodType.COCONUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(COCONUT_SIGN.get())));
    public static final Supplier<ModCeilingHangingSignBlock> COCONUT_HANGING_SIGN = CommonPlatformHelper.registerBlock("coconut_hanging_sign", () -> new ModCeilingHangingSignBlock(ModWoodType.COCONUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallHangingSignBlock> COCONUT_WALL_HANGING_SIGN = CommonPlatformHelper.registerBlock("coconut_wall_hanging_sign", () -> new ModWallHangingSignBlock(ModWoodType.COCONUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(COCONUT_HANGING_SIGN.get())));
    public static final Supplier<HangingCoconutBlock> HANGING_COCONUT = CommonPlatformHelper.registerBlock("hanging_coconut", () -> new HangingCoconutBlock(Properties.of().randomTicks().strength(2.0F, 3.0F).pushReaction(PushReaction.DESTROY).sound(SoundType.WOOD).noOcclusion()));
    public static final Supplier<CoconutBlock> COCONUT = registerBlock("coconut", CoconutBlock::new);
    public static final Supplier<SaplingBlock> COCONUT_SEEDLING = registerBlock("coconut_seedling", () -> new CoconutSaplingBlock(ModTreeGrower.COCONUT, Properties.of().noCollission().randomTicks().instabreak().sound(SoundType.GRASS)));
    public static final Supplier<FlowerPotBlock> POTTED_COCONUT_SEEDLING = CommonPlatformHelper.registerBlock("potted_coconut_seedling", () -> new FlowerPotBlock(ModBlocks.COCONUT_SEEDLING.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final Supplier<SeashellBlock> SEASHELL = registerBlock("seashell", SeashellBlock::new);
    public static final Supplier<SandcastleBlock> SANDCASTLE = CommonPlatformHelper.registerBlock("sandcastle", () -> new SandcastleBlock(Properties.of().mapColor(MapColor.SAND).strength(0.7F).sound(SoundType.SAND).pushReaction(PushReaction.DESTROY).noOcclusion().randomTicks()));
    public static final Supplier<Block> SEASHELL_BLOCK = registerBlock("seashell_block", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BROWN).strength(1.5F, 6.0F).sound(SoundType.DEEPSLATE_TILES).requiresCorrectToolForDrops()));
    public static final Supplier<Block> SEASHELL_TILES = registerBlock("seashell_tiles", () -> new Block(BlockBehaviour.Properties.ofFullCopy(SEASHELL_BLOCK.get())));
    public static final Supplier<StairBlock> SEASHELL_TILE_STAIRS = registerBlock("seashell_tile_stairs", () -> new StairBlock(SEASHELL_BLOCK.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(SEASHELL_BLOCK.get())));
    public static final Supplier<SlabBlock> SEASHELL_TILE_SLAB = registerBlock("seashell_tile_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(SEASHELL_BLOCK.get())));
    public static final Supplier<WallBlock> SEASHELL_TILE_WALL = registerBlock("seashell_tile_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(SEASHELL_BLOCK.get())));
    public static final Supplier<PricklyPearBlock> PRICKLY_PEAR = CommonPlatformHelper.registerBlock("prickly_pear", PricklyPearBlock::new);
    public static final Supplier<PotBlock> POT = registerBlock("pot", () -> new PotBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(1.0F)));
    public static final Supplier<ThinIceBlock> THIN_ICE = registerBlock("thin_ice", ThinIceBlock::new);
    public static final Supplier<Block> ICE_BRICKS = registerBlock("ice_bricks", () -> new Block(BlockBehaviour.Properties.of().friction(0.98F).strength(0.5F).sound(SoundType.GLASS)));
    public static final Supplier<StairBlock> ICE_BRICK_STAIRS = registerBlock("ice_brick_stairs", () -> new StairBlock(ICE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(ICE_BRICKS.get())));
    public static final Supplier<SlabBlock> ICE_BRICK_SLAB = registerBlock("ice_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(ICE_BRICKS.get())));
    public static final Supplier<WallBlock> ICE_BRICK_WALL = registerBlock("ice_brick_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(ICE_BRICKS.get())));
    public static final Supplier<Block> SNOW_BRICKS = registerBlock("snow_bricks", () -> new Block(BlockBehaviour.Properties.of().strength(0.5F).sound(SoundType.SNOW)));
    public static final Supplier<StairBlock> SNOW_BRICK_STAIRS = registerBlock("snow_brick_stairs", () -> new StairBlock(SNOW_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(SNOW_BRICKS.get())));
    public static final Supplier<SlabBlock> SNOW_BRICK_SLAB = registerBlock("snow_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(SNOW_BRICKS.get())));
    public static final Supplier<WallBlock> SNOW_BRICK_WALL = registerBlock("snow_brick_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(SNOW_BRICKS.get())));
    public static final Supplier<RotatedPillarBlock> WALNUT_LOG = registerBlock("walnut_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LOG)));
    public static final Supplier<RotatedPillarBlock> STRIPPED_WALNUT_LOG = registerBlock("stripped_walnut_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_LOG)));
    public static final Supplier<RotatedPillarBlock> WALNUT_WOOD = registerBlock("walnut_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD)));
    public static final Supplier<RotatedPillarBlock> STRIPPED_WALNUT_WOOD = registerBlock("stripped_walnut_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_WOOD)));
    public static final Supplier<LeavesBlock> WALNUT_LEAVES = registerBlock("walnut_leaves", () -> new LeavesBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES)));
    public static final Supplier<Block> WALNUT_PLANKS = registerBlock("walnut_planks", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<SlabBlock> WALNUT_SLAB = registerBlock("walnut_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<StairBlock> WALNUT_STAIRS = registerBlock("walnut_stairs", () -> new StairBlock(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceBlock> WALNUT_FENCE = registerBlock("walnut_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceGateBlock> WALNUT_FENCE_GATE = registerBlock("walnut_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)){});
    public static final Supplier<DoorBlock> WALNUT_DOOR = registerBlock("walnut_door", () -> new DoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_DOOR)){});
    public static final Supplier<TrapDoorBlock> WALNUT_TRAPDOOR = registerBlock("walnut_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_TRAPDOOR)){});
    public static final Supplier<ButtonBlock> WALNUT_BUTTON = registerBlock("walnut_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON)) {});
    public static final Supplier<PressurePlateBlock> WALNUT_PRESSURE_PLATE = registerBlock("walnut_pressure_plate", () -> new PressurePlateBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE)) {});
    public static final Supplier<ModStandingSignBlock> WALNUT_SIGN = CommonPlatformHelper.registerBlock("walnut_sign", () -> new ModStandingSignBlock(ModWoodType.WALNUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallSignBlock> WALNUT_WALL_SIGN = CommonPlatformHelper.registerBlock("walnut_wall_sign", () -> new ModWallSignBlock(ModWoodType.WALNUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(WALNUT_SIGN.get())));
    public static final Supplier<ModCeilingHangingSignBlock> WALNUT_HANGING_SIGN = CommonPlatformHelper.registerBlock("walnut_hanging_sign", () -> new ModCeilingHangingSignBlock(ModWoodType.WALNUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallHangingSignBlock> WALNUT_WALL_HANGING_SIGN = CommonPlatformHelper.registerBlock("walnut_wall_hanging_sign", () -> new ModWallHangingSignBlock(ModWoodType.WALNUT, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(WALNUT_HANGING_SIGN.get())));
    public static final Supplier<SaplingBlock> WALNUT_SAPLING = registerBlock("walnut_sapling", () -> new SaplingBlock(ModTreeGrower.WALNUT, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING)){});
    public static final Supplier<FlowerPotBlock> POTTED_WALNUT_SAPLING = CommonPlatformHelper.registerBlock("potted_walnut_sapling", () -> new FlowerPotBlock(ModBlocks.WALNUT_SAPLING.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final Supplier<AzaleaLogBlock> AZALEA_LOG = registerBlock("azalea_log", AzaleaLogBlock::new);
    public static final Supplier<FloweringAzaleaLogBlock> FLOWERING_AZALEA_LOG = registerBlock("flowering_azalea_log", FloweringAzaleaLogBlock::new);
    public static final Supplier<RotatedPillarBlock> STRIPPED_AZALEA_LOG = registerBlock("stripped_azalea_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_LOG)));
    public static final Supplier<RotatedPillarBlock> AZALEA_WOOD = registerBlock("azalea_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD)));
    public static final Supplier<FloweringAzaleaLogBlock> FLOWERING_AZALEA_WOOD = registerBlock("flowering_azalea_wood", FloweringAzaleaLogBlock::new);
    public static final Supplier<RotatedPillarBlock> STRIPPED_AZALEA_WOOD = registerBlock("stripped_azalea_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_OAK_WOOD)));
    public static final Supplier<Block> AZALEA_PLANKS = registerBlock("azalea_planks", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<Block> FLOWERING_AZALEA_PLANKS = registerBlock("flowering_azalea_planks", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<SlabBlock> AZALEA_SLAB = registerBlock("azalea_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<SlabBlock> FLOWERING_AZALEA_SLAB = registerBlock("flowering_azalea_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<StairBlock> AZALEA_STAIRS = registerBlock("azalea_stairs", () -> new StairBlock(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<StairBlock> FLOWERING_AZALEA_STAIRS = registerBlock("flowering_azalea_stairs", () -> new StairBlock(Blocks.OAK_PLANKS.defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceBlock> AZALEA_FENCE = registerBlock("azalea_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceBlock> FLOWERING_AZALEA_FENCE = registerBlock("flowering_azalea_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceGateBlock> AZALEA_FENCE_GATE = registerBlock("azalea_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<FenceGateBlock> FLOWERING_AZALEA_FENCE_GATE = registerBlock("flowering_azalea_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PLANKS)));
    public static final Supplier<DoorBlock> AZALEA_DOOR = registerBlock("azalea_door", () -> new DoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_DOOR)){});
    public static final Supplier<DoorBlock> FLOWERING_AZALEA_DOOR = registerBlock("flowering_azalea_door", () -> new DoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_DOOR)){});
    public static final Supplier<TrapDoorBlock> AZALEA_TRAPDOOR = registerBlock("azalea_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_TRAPDOOR)){});
    public static final Supplier<TrapDoorBlock> FLOWERING_AZALEA_TRAPDOOR = registerBlock("flowering_azalea_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_TRAPDOOR)){});
    public static final Supplier<ButtonBlock> AZALEA_BUTTON = registerBlock("azalea_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_BUTTON)) {});
    public static final Supplier<PressurePlateBlock> AZALEA_PRESSURE_PLATE = registerBlock("azalea_pressure_plate", () -> new PressurePlateBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_PRESSURE_PLATE)) {});
    public static final Supplier<AzaleaFlowerBlock> AZALEA_FLOWER = registerBlock("azalea_flower", AzaleaFlowerBlock::new);
    public static final Supplier<SurfaceMossBlock> SURFACE_MOSS = registerBlock("surface_moss", () -> new SurfaceMossBlock(Properties.of().mapColor(MapColor.COLOR_GREEN).noCollission().strength(0.2F).pushReaction(PushReaction.DESTROY).sound(SoundType.MOSS_CARPET).noOcclusion()));
    public static final Supplier<MossLayerBlock> MOSS_LAYER = CommonPlatformHelper.registerBlock("moss_layer", MossLayerBlock::new);
    public static final Supplier<FlowerPotBlock> POTTED_AZALEA_FLOWER = CommonPlatformHelper.registerBlock("potted_azalea_flower", () -> new FlowerPotBlock(ModBlocks.AZALEA_FLOWER.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final Supplier<ModStandingSignBlock> AZALEA_SIGN = CommonPlatformHelper.registerBlock("azalea_sign", () -> new ModStandingSignBlock(ModWoodType.AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallSignBlock> AZALEA_WALL_SIGN = CommonPlatformHelper.registerBlock("azalea_wall_sign", () -> new ModWallSignBlock(ModWoodType.AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(AZALEA_SIGN.get())));
    public static final Supplier<ModCeilingHangingSignBlock> AZALEA_HANGING_SIGN = CommonPlatformHelper.registerBlock("azalea_hanging_sign", () -> new ModCeilingHangingSignBlock(ModWoodType.AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallHangingSignBlock> AZALEA_WALL_HANGING_SIGN = CommonPlatformHelper.registerBlock("azalea_wall_hanging_sign", () -> new ModWallHangingSignBlock(ModWoodType.AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(AZALEA_HANGING_SIGN.get())));
    public static final Supplier<ModStandingSignBlock> FLOWERING_AZALEA_SIGN = CommonPlatformHelper.registerBlock("flowering_azalea_sign", () -> new ModStandingSignBlock(ModWoodType.FLOWERING_AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallSignBlock> FLOWERING_AZALEA_WALL_SIGN = CommonPlatformHelper.registerBlock("flowering_azalea_wall_sign", () -> new ModWallSignBlock(ModWoodType.FLOWERING_AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(FLOWERING_AZALEA_SIGN.get())));
    public static final Supplier<ModCeilingHangingSignBlock> FLOWERING_AZALEA_HANGING_SIGN = CommonPlatformHelper.registerBlock("flowering_azalea_hanging_sign", () -> new ModCeilingHangingSignBlock(ModWoodType.FLOWERING_AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD)));
    public static final Supplier<ModWallHangingSignBlock> FLOWERING_AZALEA_WALL_HANGING_SIGN = CommonPlatformHelper.registerBlock("flowering_azalea_wall_hanging_sign", () -> new ModWallHangingSignBlock(ModWoodType.FLOWERING_AZALEA, BlockBehaviour.Properties.of().noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(FLOWERING_AZALEA_HANGING_SIGN.get())));
    
    public static <T extends Block> Supplier<T> registerBlock(String name, Supplier<T> block) {
        Supplier<T> toReturn = CommonPlatformHelper.registerBlock(name, block);
        CommonPlatformHelper.registerItem(name, () -> new BlockItem(toReturn.get(), new Item.Properties()));
        return toReturn;
    }
}
